# PostgreSQL Database Configurations
db.url=jdbc:postgresql://localhost:5432/university_db
db.username=postgres
db.password=admin
db.driver-class-name=org.postgresql.Driver

# Connection Pool Configurations
db.hikari.maximum-pool-size=10
db.hikari.minimum-idle=2
db.hikari.idle-timeout=30000
db.hikari.connection-timeout=20000
